### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ChildishGiant** [ThaCuber/Playtris#27]
Currently the latest release is behind main, missing some bug fixes and the old name 👀

**Comment by thacuber2a03** [comment]
I wanna refactor the code before doing so though, it's a total mess and some files are unneeded, like wallkickdata.lua and tspindata.lua

**Comment by thacuber2a03** [comment]
that should be done now
also, the launcher card will stay as is until I draw a better one
that is, *if* I draw a better one
