### ISSUE TITLE
It'd be delightful to be able to make blocks in the grid 13x13 instead of 11x11

### ISSUE THREAD

**Issue by obra** [ThaCuber/Playtris#3]
Making that configurable so will require redoing a bit of the layout code for metadata, since a lot of the layout is based around screen units of blockSize.

If this is something that'd be desirable, I wouldn't mind hacking on it, but if it's not something you want to do, I won't meddle.

**Comment by thacuber2a03** [comment]
Well, it is possible to do, but the problem is that it looks kinda crowded, like there's not enough space on the screen (this is a really bad showcase of it):
![image](https://user-images.githubusercontent.com/70547062/167165971-7e80d006-0ba6-4593-be6c-ee3a0160e36c.png)
Plus, I'd have to redesign the assets and adjust most of the code, so sorry, but I can't accept.

**Comment by obra** [comment]
My eyes aren't as good as they once were, so I'd find an option for easier to see tetrominos even if it's not quite as pretty 

I started in on an implementation of this (as a configurable option) before stepping back and opening the issue once I realized how much refactoring would be needed. 

What I had done was to add a block size param to the piece drawing method, which let me stick with smaller pieces for next and hold (since that has some historical precedent in handheld *tris implementations.)

That part worked just great, but it became clear that the score and level information code would need a bunch of refactoring to make configurable block sizes work cleanly. 

I'm happy to do that refactoring and to implement 12x12 or 13x13 as an option, but if you're sure you'd never take it, I won't push it on you.

**Comment by thacuber2a03** [comment]
Well, if you can make it look nice, you can implement them, it might be better for people that can't really see very well (as is your case)

**Comment by obra** [comment]
Cool. I’ll take a swing at it as a PR against the dev branch.

**Comment by thacuber2a03** [comment]
First let me update said branch.

**Comment by thacuber2a03** [comment]
I did it some minutes ago but forgor to say it

**Comment by obra** [comment]
👍🏼

**Comment by obra** [comment]
Now merged.
