### ISSUE TITLE
[Suggestion] Tag releases to easily keep track of changes

### ISSUE THREAD

**Issue by mikedinicola** [ThaCuber/Playtris#8]
I'd suggest tagging releases. So far releases have been quick with few changes in between, but that may change in the future and it will make developing easier if releases are tagged. Players might find this useful as well.

I've put up an example release on my fork, including content from the itch page: https://github.com/mikedinicola/Playtris/releases/tag/1.5.1

**Comment by thacuber2a03** [comment]
a yes

**Comment by mikedinicola** [comment]
😄
